include outputs/hpd0.conf

include inputs/pointer.conf
include inputs/touchpad.conf
include inputs/keyboard.conf

#include bar/hpd0.conf

#include windows/module.conf

include chrome/module.conf

include autostart/module.conf
