include variables/ispl0.conf

include outputs/ispl0.conf

include inputs/pointer.conf
include inputs/touchpad.conf
include inputs/keyboard.conf

#include bar/ispl0.conf

#include windows/module.conf

include chrome/module.conf

include autostart/ispl0.conf
