#!/usr/bin/env bash

MDE_BG_CONFIG="${XDG_CONFIG_HOME:-${HOME}/.config}/mde/background"
MDE_BG_PICTURES_DIR="${MDE_BG_PICTURES_DIR:-$(xdg-user-dir PICTURES)}"

load_bg() {
  [ -r "$MDE_BG_CONFIG" ] && read -r bg <"$MDE_BG_CONFIG"

  pkill -x swaybg

  swaybg -o '*' -i "$bg" -m fill &
}

start_bg_watcher() {
  # shellcheck disable=SC2034
  # We know we're not reading the event, but we can't not set a variable at all
  inotifywait -qme close_write "$MDE_BG_CONFIG" |
    while read -r event; do
      load_bg
    done
}

set_bg() {
  local bg="$1"

  echo "$bg" >"$MDE_BG_CONFIG"
}

select_bg() {
  imv_config="${HOME}/.config/imv/mde-bg-select.config" imv -r "$MDE_BG_PICTURES_DIR"
}

declare -r cmd="$1"
shift

while getopts :d: opt; do
  case "$opt" in
    d)
      MDE_BG_PICTURES_DIR="$OPTARG"
      ;;
    *)
      echo "Unrecognized option $opt"
      ;;
  esac
done

shift $((OPTIND - 1))

case "$cmd" in
'set')
  set_bg "$1"
  ;;
'reload')
  load_bg
  ;;
'start')
  # Since we're starting the watcher,
  # make sure we have a background in the first place
  load_bg
  start_bg_watcher
  ;;
'select')
  select_bg
  ;;
*)
  echo 'Unsupported command!'
  exit 1
  ;;
esac
