# Make things pretty
exec mde bg start
exec mde bar start

# Handle screen idling
exec swayidle timeout 14400 $lock

# Set up clipboard history
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
