bar {
   position top
   font $uifont
   status_command while ~/.config/sway/scripts/sway_bar.sh; do sleep 1; done

   colors {
       statusline $color_fg
       background $color_bgF2
       inactive_workspace #323232 #323232 #5c5c5c
   }
}
