#!/bin/sh

# Start compositor
compton &

# Set desktop colors.
xrdb -merge ~/.cache/wal/bspwm-colors.xresources

# Start notification daemon.
dunst_wrapper &

# Set background.
~/.fehbg

# Start panels.
start-panels &
