#!/bin/sh

sxhkd &

. $HOME/.config/profile.d/bspwm.sh

BORDER_WIDTH=${_border_width:-0}
LEFT_PADDING=${_left_padding:-480}
RIGHT_PADDING=${_right_padding:-0}
TOP_PADDING=${_top_padding:-32}
BOTTOM_PADDING=${_bottom_padding:-0}
WINDOW_GAP=${_window_gap:-32}

_MONITORS=( $(xrandr --listactivemonitors | awk 'FNR > 1 {print $NF}') )

i=1

for mon in ${_MONITORS[@]}
do
  bspc monitor $mon -d wksp_${i}_1
  for j in {2..4}
  do
    bspc monitor $mon -a wksp_${i}_${j}
  done
  i=$(( $i + 1 ))
done

unset i

bspc config border_width     $BORDER_WIDTH
bspc config window_gap         $WINDOW_GAP
bspc config top_padding       $TOP_PADDING
bspc config bottom_padding $BOTTOM_PADDING
bspc config left_padding     $LEFT_PADDING
bspc config right_padding   $RIGHT_PADDING

bspc config split_ratio              0.50

# Wasteful, but attractive.
bspc config borderless_monocle      false
bspc config gapless_monocle         false

# Pointer settings.
bspc config click_to_focus           true
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false

# Pointer events.
bspc config pointer_modifier      control
bspc config pointer_action1   resize_side
bspc config pointer_action2 resize_corner
bspc config pointer_action3          move

bspc rule -a Gimp     state=floating
bspc rule -a mpv     state=floating sticky=on focus=off
#bspc rule -a mpv      state=tiled desktop=^3
bspc rule -a Surf     state=tiled
bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"

${HOME}/.config/bspwm/autostart &
