#!/bin/sh

sxhkd &

bspc monitor DVI-1 -n LG      -d Unu Du Tri
bspc monitor DVI-0 -n Samsung -d Kvar Kvin Ses

bspc config border_width               2
bspc config window_gap                32

# Padding for pixel space above the panel.
# Chintzy and wasteful? Sure. But nice-looking.
bspc config top_padding               40
bspc config bottom_padding \
$(bspc config top_padding)

bspc config left_padding              64
bspc config right_padding \
$(bspc config left_padding)

bspc config split_ratio              0.50

# Against, wasteful, but attractive
bspc config borderless_monocle       false
bspc config gapless_monocle          false

# Pointer settings.
bspc config click_to_focus        button1
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false

# Pointer events.
bspc config pointer_modifier      control
bspc config pointer_action1 resize_corner
bspc config pointer_action3          move

bspc rule -a Gimp      desktop='^8' state=floating follow=on
bspc rule -a Chromium  desktop='^2'
bspc rule -a mpv       desktop='^4'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a '*:yad'   state=floating
bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"

${HOME}/.config/bspwm/autostart &
