#!/bin/bash

declare -ra TAB_ALLOWED_WINDOWS=('firefox' 'tym')

get_window_class() {
  xprop WM_CLASS -id "$1" | cut -d\= -f2 | awk -F'=' '{gsub(/^\s*|[",]/, ""); print}'
}

tabs_allowed() {
  [[ "$1" =~ "" ]]
}

declare -r window_id="$1"
declare -r window_name="$2"
