#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:filetype=python

import urllib.request, json

city = "denver,us"
api_key = "$api_key"
units = "imperial"
unit_key = "F"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}&units={}".format(city, api_key, units)).read())[2:-1])

temp = int(float(weather["main"]["temp"]))

print("%i° %s" % (temp, unit_key))
